require: rubocop-rspec

inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'bin/*'
    - 'app/services/beers_feeder.rb'
    - 'app/helpers/form_tag_helper.rb'

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Style/DateTime:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'
    - config/routes.rb
